#!/usr/bin/env ruby

require "bundler/setup"
require "speed/daemon"

api_host = ENV["SPEED_DAEMON_API_HOST"]

if api_host.nil?
  raise Speed::Daemon::ConfigurationError, "SPEED_DAEMON_API_HOST env var must be set."
else
  http_client = Faraday.new(url: api_host) do |faraday|
    faraday.adapter  Faraday.default_adapter
  end

  Speed::Daemon::Runner.new(
    speed: Speed::Daemon::Speed.new,
    network: Speed::Daemon::Network.new,
    client: Speed::Daemon::Client.new(http_client),
    logger: Speed::Daemon::Logger.new(STDOUT)
  ).run
end
