#!/usr/bin/env ruby

require "bundler/setup"
require "speed/daemon"

api_host = "https://unboxed-pickles.herokuapp.com"

http_client = Faraday.new(url: api_host) do |faraday|
  faraday.adapter  Faraday.default_adapter
end

Pickles::Daemon::Runner.new(
  speed: Pickles::Daemon::Speed.new,
  network: Pickles::Daemon::Network.new,
  client: Pickles::Daemon::Client.new(http_client),
  logger: Pickles::Daemon::Logger.new(STDOUT)
).run
